ref:
  as: platform-external-ccm-deploy
  from: cli
  commands: platform-external-ccm-deploy-commands.sh
  grace_period: 20m
  resources:
    requests:
      cpu: 10m
      memory: 100Mi
  documentation: |-
    The IPI AWS configure step generates the AWS-specific install-config.yaml contents based on the cluster profile and optional input files.
  env:
  - name: PLATFORM_EXTERNAL_CCM_ENABLED
    default: "no"
    documentation: |-
      Allow installing CCM.
