#!/bin/bash

set -o nounset
set -o errexit
set -o pipefail

#
# Teardown for a `platform: external` cluster provisioned by a user-supplied
# Cluster API provider. See the ref documentation for why this is a restore
# followed by a delete rather than a resource sweep.
#

source "${SHARED_DIR}/init-fn.sh"
source "${SHARED_DIR}/capi-fn.sh"

install_jq

: "${PLATFORM_EXTERNAL_CAPI_CLOUD:?set it to aws or oci}"
: "${PLATFORM_EXTERNAL_CAPI_EXAMPLE:?set it to the example the install used}"
: "${PLATFORM_EXTERNAL_CAPI_ARTIFACTS:?set it to the artifact directory the install used}"

export CAPI_ARTIFACTS="${PLATFORM_EXTERNAL_CAPI_ARTIFACTS}"

INSTALL_DIR=/tmp/install-dir
EXAMPLE_DIR=$(capi_example_dir "${PLATFORM_EXTERNAL_CAPI_EXAMPLE}")

# An install that never created a Cluster left nothing to remove. Exiting 0
# here keeps the real failure visible instead of burying it under a teardown
# failure that is only its consequence.
if [[ ! -f ${SHARED_DIR}/metadata.json ]]; then
  capi_log "No metadata.json was saved by the install step, so no cluster was"
  capi_log "created and there is nothing to destroy."
  exit 0
fi

capi_restore_destroy_state "${INSTALL_DIR}" "${EXAMPLE_DIR}"

# --------------------------------------------------------- provider artifacts

case "${PLATFORM_EXTERNAL_CAPI_CLOUD}" in
aws)
  capi_stage_embedded_provider "${PLATFORM_EXTERNAL_CAPI_PROVIDER:-aws}"
  ;;
oci)
  capi_stage_capoci "${EXAMPLE_DIR}" \
    "${PLATFORM_EXTERNAL_CAPI_PROVIDER_IMAGE}" \
    "${PLATFORM_EXTERNAL_CAPI_COMPONENTS_URL}"
  ;;
esac

# The paths in metadata.json are what `destroy cluster` actually opens. Check
# them against what was just staged rather than trusting that the install step
# and this one agree -- they are two statements of the same fact.
for field in binaryPath componentsPath; do
  recorded=$(jq -r ".external.clusterAPI.${field} // empty" "${INSTALL_DIR}/metadata.json")
  if [[ -n ${recorded} && ! -e ${recorded} ]]; then
    capi_log "ERROR: metadata.json records ${field}=${recorded}, which does not exist"
    capi_log "       after staging into ${CAPI_ARTIFACTS}. The install and the"
    capi_log "       teardown disagree about where the provider lives."
    exit 1
  fi
done

# ------------------------------------------------------------- cloud identity

case "${PLATFORM_EXTERNAL_CAPI_CLOUD}" in
aws)
  install_awscli
  : "${LEASED_RESOURCE:?no AWS region lease}"
  export AWS_REGION="${LEASED_RESOURCE}"
  export AWS_DEFAULT_REGION="${AWS_REGION}"
  # CAPA reads this itself. Passed by path and never read here.
  export AWS_SHARED_CREDENTIALS_FILE="${CLUSTER_PROFILE_DIR}/.awscred"
  ;;
oci)
  capi_install_oci_cli
  capi_oci_cli_config

  # Put CAPOCI's credential Secret back, for the reason set out in the ref
  # documentation. loadArtifacts globs *.yaml and the restore's second phase
  # -- everything that is neither the Namespace nor the core Cluster -- is
  # where a Secret lands, which is before the Cluster that needs it. So
  # dropping the manifest in is sufficient and nothing else has to change.
  # The name has to be the one OCIClusterIdentity.spec.principalSecret
  # records, which is <infra-id>-oci-credentials. Taken from metadata.json
  # rather than reconstructed, because the infrastructure ID is generated by
  # the installer and nothing else here knows it.
  INFRA_ID=$(jq -r '.infraID' "${INSTALL_DIR}/metadata.json")
  mkdir -p "${INSTALL_DIR}/.clusterapi_output"
  capi_oci_identity_secret \
    "${INSTALL_DIR}/.clusterapi_output/00-restored-oci-credentials.yaml" \
    "${INFRA_ID}-oci-credentials"
  ;;
*)
  capi_log "ERROR: unknown cloud ${PLATFORM_EXTERNAL_CAPI_CLOUD}"
  exit 1
  ;;
esac

# ------------------------------------------------------------------- teardown

capi_log "Destroying the cluster"
set +o errexit
openshift-install destroy cluster --log-level=debug --dir="${INSTALL_DIR}" &
wait "$!"
ret=$?
set -o errexit

cp -v "${INSTALL_DIR}/.openshift_install.log" "${ARTIFACT_DIR}/openshift_destroy.log" 2>/dev/null || true

# Independent check for the one thing whose survival is worse than a leaked
# machine: the bootstrap ignition object and the unauthenticated URL over it.
# A preDestroy hook that silently did nothing and one that worked are
# indistinguishable from the installer's exit code.
IGNITION_STATE="${INSTALL_DIR}/.external-hook-state/bootstrap-ignition.json"
if [[ ${PLATFORM_EXTERNAL_CAPI_CLOUD} == "oci" && -f ${IGNITION_STATE} ]]; then
  BUCKET=$(jq -r '.ignitionBucket' "${IGNITION_STATE}")
  OBJECT=$(jq -r '.ignitionObject' "${IGNITION_STATE}")
  if oci os object head --bucket-name "${BUCKET}" --name "${OBJECT}" >/dev/null 2>&1; then
    capi_log "ERROR: ${OBJECT} is still in ${BUCKET}. It holds the cluster's day-0"
    capi_log "       secrets and the pre-authenticated request over it may still be live."
    oci os object delete --bucket-name "${BUCKET}" --object-name "${OBJECT}" --force || true
    ret=1
  else
    capi_log "bootstrap ignition object is gone from ${BUCKET}"
  fi
fi

exit "${ret}"
