build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: rhel-8-release-golang-1.20-openshift-4.15
images:
- dockerfile_path: Dockerfile
  from: src
  to: ipog
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: build-publish-preview
  commands: |
    echo "#> Publishing preview site to artifacts (GCS)"
    cp -rf /opt/site /logs/artifacts/site
  container:
    from: ipog
zz_generated_metadata:
  branch: main
  org: openshift
  repo: infrastructure-provider-onboarding-guide
