base_images:
  cli:
    name: "4.14"
    namespace: ocp
    tag: cli
  upi-installer:
    name: "4.14"
    namespace: ocp
    tag: upi-installer
binary_build_commands: make linux-amd64
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.19
images:
- dockerfile_literal: |
    # https://github.com/redhat-openshift-ecosystem/provider-certification-tool/pull/38
    FROM quay.io/ocp-cert/opct-runner:0.0.0-dev.92-5763394953
    COPY oc /usr/bin/oc
    COPY openshift-install /usr/bin/openshift-install
    RUN ln -s /usr/bin/oc /usr/bin/kubectl
    #    && curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" \
    #    && unzip -q awscliv2.zip && ./aws/install -b /bin \
    #    && rm -rf ./aws awscliv2.zip
  inputs:
    cli:
      paths:
      - destination_dir: .
        source_path: /usr/bin/oc
    upi-installer:
      paths:
      - destination_dir: .
        source_path: /bin/openshift-install
  to: opct-runner
releases:
  latest:
    release:
      architecture: amd64
      channel: candidate
      version: "4.14"
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
  upi-installer:
    requests:
      cpu: "3"
      memory: 5Gi
tests:
- as: platform-external-vsphere
  cron: 0 0 * * 6
  steps:
    cluster_profile: vsphere-2
    env:
      OPCT_DEV_EXTRA_CMD: --plugins-image=openshift-tests-provider-cert:devel
    workflow: opct-flow-platform-external-vsphere
  timeout: 4h0m0s
- as: platform-none-vsphere
  cron: 0 0 * * 6
  steps:
    cluster_profile: vsphere
    workflow: opct-flow-platform-none-vsphere
  timeout: 4h0m0s
- as: platform-external-oci
  cron: 0 0 * * 1
  steps:
    cluster_profile: aws
    env:
      CLUSTER_REGION: us-sanjose-1
      OPCT_CUSTOM_PLUGIN_IMAGE: openshift-tests-provider-cert:devel
      OPCT_DOMAIN: splat-oci.devcluster.openshift.com
    workflow: opct-flow-platform-external-oci
  timeout: 6h0m0s
- as: platform-none-aws
  cron: 0 0 * * 1
  steps:
    cluster_profile: aws
    env:
      CLUSTER_REGION: us-east-1
      OPCT_CUSTOM_PLUGIN_IMAGE: openshift-tests-provider-cert:devel
      OPCT_DOMAIN: devcluster.openshift.com
    workflow: opct-flow-platform-none-aws
  timeout: 6h0m0s
zz_generated_metadata:
  branch: main
  org: redhat-openshift-ecosystem
  repo: provider-certification-tool
  variant: "4.14"
