base_images:
  upi-installer:
    name: "4.17"
    namespace: ocp
    tag: upi-installer
  cli:
    name: "4.17"
    namespace: ocp
    tag: cli
binary_build_commands: make linux-amd64
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.21
images:
- dockerfile_literal: |
    FROM quay.io/ocp-cert/opct:v0.5.0-alpha.3 as opct
    FROM quay.io/fedora/fedora-minimal:40
    WORKDIR /tmp
    COPY oc /usr/bin/oc
    COPY --from=opct /usr/bin/opct-linux-amd64 /usr/bin/opct
    # https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html
    ADD "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" ./awscliv2.zip
    ADD https://github.com/mikefarah/yq/releases/download/v4.33.3/yq_linux_amd64 /usr/bin/yq
    RUN  microdnf install -y zip \
        && unzip awscliv2.zip \
        && microdnf clean all \
        && ./aws/install \
        && aws --version \
        && rm -f awscliv2.zip \
        && chmod u+x /usr/bin/yq \
        && chmod u+x /usr/bin/oc \
        && chmod u+x /usr/bin/opct
  inputs:
    cli:
      paths:
      - destination_dir: .
        source_path: /usr/bin/oc
    # opct:
    #   paths:
    #   - destination_dir: .
    #     source_path: /usr/bin/opct-linux-amd64
  to: opct-runner
releases:
  initial:
    integration:
      name: "4.17"
      namespace: ocp
  latest:
    integration:
      include_built_images: true
      name: "4.17"
      namespace: ocp
  multi-latest:
    candidate:
      architecture: multi
      product: ocp
      stream: nightly
      version: "4.17"
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
  upi-installer:
    requests:
      cpu: "3"
      memory: 5Gi
tests:
- always_run: false
  as: platform-none-vsphere
  optional: true
  steps:
    cluster_profile: vsphere-elastic
    env:
      OPCT_CLI_IMAGE: quay.io/ocp-cert/opct:v0.5.0-alpha.4
      OPCT_DEV_EXTRA_CMD: "--dev-count=10"
    workflow: opct-test-platform-none-vsphere
  timeout: 6h0m0s
- always_run: false
  as: platform-external-vsphere
  optional: true
  steps:
    cluster_profile: vsphere-elastic
    env:
      OPCT_DEV_EXTRA_CMD: --plugins-image=plugin-openshift-tests:latest
      PLATFORM_NAME: vsphere
    workflow: opct-test-platform-external-vsphere
  timeout: 6h0m0s
- always_run: false
  as: platform-none-vsphere-upgrade
  optional: true
  steps:
    cluster_profile: vsphere-elastic
    env:
      OPCT_RUN_MODE: upgrade
      UPGRADE_TO_CHANNEL_TYPE: candidate
    workflow: opct-test-platform-none-vsphere
  timeout: 8h0m0s
zz_generated_metadata:
  branch: main
  org: redhat-openshift-ecosystem
  repo: provider-certification-tool
