base_images:
  cli:
    name: "4.13"
    namespace: ocp
    tag: cli
  upi-installer:
    name: "4.13"
    namespace: ocp
    tag: upi-installer
binary_build_commands: make linux-amd64
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.19
images:
- dockerfile_literal: |
    FROM quay.io/ocp-cert/opct-runner:0.0.0-dev.92-5763394953
    COPY oc /usr/bin/oc
    COPY openshift-install /usr/bin/openshift-install
    RUN ln -s /usr/bin/oc /usr/bin/kubectl
  inputs:
    cli:
      paths:
      - destination_dir: .
        source_path: /usr/bin/oc
    upi-installer:
      paths:
      - destination_dir: .
        source_path: /bin/openshift-install
  to: opct-runner
releases:
  latest:
    release:
      architecture: amd64
      channel: fast
      version: "4.13"
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
  upi-installer:
    requests:
      cpu: "3"
      memory: 5Gi
tests:
- as: platform-none-vsphere
  cron: 0 0 * * 1
  steps:
    cluster_profile: vsphere
    workflow: opct-flow-platform-none-vsphere
  timeout: 4h0m0s
- as: platform-external-vsphere
  cron: 0 0 * * 1
  steps:
    cluster_profile: vsphere
    workflow: opct-flow-platform-external-vsphere
  timeout: 4h0m0s
- as: platform-external-oci
  cron: 0 0 * * 1
  steps:
    cluster_profile: aws
    env:
      CLUSTER_REGION: us-sanjose-1
      OPCT_CUSTOM_PLUGIN_IMAGE: openshift-tests-provider-cert:devel
      OPCT_DOMAIN: splat-oci.devcluster.openshift.com
      OPCT_SETUP_REGISTRY_LOCAL: "yes"
      PATCH_INFRA_MANIFEST: "true"
    workflow: opct-flow-platform-external-oci
  timeout: 4h0m0s
zz_generated_metadata:
  branch: main
  org: redhat-openshift-ecosystem
  repo: provider-certification-tool
  variant: "4.13"
