base_images:
  upi-installer:
    name: "4.14"
    namespace: ocp
    tag: upi-installer
  cli:
    name: "4.17"
    namespace: ocp
    tag: cli
binary_build_commands: make linux-amd64
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.21
images:
- dockerfile_literal: |
    FROM quay.io/ocp-cert/opct:v0.5.0-alpha.1
    WORKDIR /opct
    COPY oc /usr/bin/oc
    # https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html
    ADD "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" ./awscliv2.zip
    RUN  microdnf install zip \
        && unzip awscliv2.zip && ./aws/install \
        && aws --version \
        && rm -f awscliv2.zip  \
        && microdnf clean all
  inputs:
    cli:
      paths:
      - destination_dir: .
        source_path: /usr/bin/oc
  to: opct-runner
releases:
  latest:
    release:
      architecture: amd64
      channel: fast
      version: "4.14"
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
  upi-installer:
    requests:
      cpu: "3"
      memory: 5Gi
tests:
- as: platform-none-vsphere
  cron: 0 0 * * 6
  steps:
    cluster_profile: vsphere-elastic
    env:
      OPCT_DEV_EXTRA_CMD: --plugins-image=openshift-tests-provider-cert:devel
    workflow: opct-test-platform-none-vsphere
  timeout: 6h0m0s
- as: platform-external-vsphere
  cron: 0 0 * * 6
  steps:
    cluster_profile: vsphere-elastic
    env:
      OPCT_DEV_EXTRA_CMD: --plugins-image=openshift-tests-provider-cert:devel
      PLATFORM_NAME: vsphere
    workflow: opct-test-platform-external-vsphere
  timeout: 6h0m0s
- as: platform-none-vsphere-upgrade
  cron: 0 0 * * 6
  steps:
    cluster_profile: vsphere-elastic
    env:
      OPCT_RUN_MODE: upgrade
      UPGRADE_TO_CHANNEL_TYPE: candidate
    workflow: opct-test-platform-none-vsphere
  timeout: 8h0m0s
zz_generated_metadata:
  branch: main
  org: redhat-openshift-ecosystem
  repo: provider-certification-tool
  variant: "4.14"
