base_images:
  upi-installer:
    name: "4.16"
    namespace: ocp
    tag: upi-installer
  cli:
    name: "4.17"
    namespace: ocp
    tag: cli
binary_build_commands: echo wontdo-use-build-image
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.21
releases:
  latest:
    candidate:
      product: ocp
      stream: nightly
      version: "4.16"
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
  upi-installer:
    requests:
      cpu: "3"
      memory: 5Gi
tests:
- as: platform-none-vsphere
  cron: 0 0 * * 4
  steps:
    cluster_profile: vsphere-elastic
    workflow: opct-test-platform-none-vsphere
  timeout: 6h0m0s
- as: platform-external-vsphere
  cron: 0 0 * * 4
  steps:
    cluster_profile: vsphere-elastic
    env:
      PLATFORM_NAME: vsphere
    workflow: opct-test-platform-external-vsphere
  timeout: 6h0m0s
zz_generated_metadata:
  branch: main
  org: redhat-openshift-ecosystem
  repo: provider-certification-tool
  variant: "4.16"
