base_images:
  upi-installer:
    name: "4.17"
    namespace: ocp
    tag: upi-installer
binary_build_commands: make linux-amd64
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.22
releases:
  initial:
    integration:
      name: "4.17"
      namespace: ocp
  latest:
    integration:
      include_built_images: true
      name: "4.17"
      namespace: ocp
  multi-latest:
    candidate:
      architecture: multi
      product: ocp
      stream: nightly
      version: "4.17"
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
  upi-installer:
    requests:
      cpu: "3"
      memory: 5Gi
tests:
- always_run: false
  as: platform-none-vsphere
  optional: true
  steps:
    cluster_profile: vsphere-elastic
    env:
      OPCT_DEV_EXTRA_CMD: --plugins-image=plugin-openshift-tests:latest
    workflow: opct-test-platform-none-vsphere
  timeout: 6h0m0s
- always_run: false
  as: platform-external-vsphere
  optional: true
  steps:
    cluster_profile: vsphere-elastic
    env:
      OPCT_DEV_EXTRA_CMD: --plugins-image=plugin-openshift-tests:latest
      PLATFORM_NAME: vsphere
    workflow: opct-test-platform-external-vsphere
  timeout: 6h0m0s
- always_run: false
  as: platform-none-vsphere-upgrade
  optional: true
  steps:
    cluster_profile: vsphere-elastic
    env:
      OPCT_RUN_MODE: upgrade
      UPGRADE_TO_CHANNEL_TYPE: candidate
    workflow: opct-test-platform-none-vsphere
  timeout: 8h0m0s
zz_generated_metadata:
  branch: main
  org: redhat-openshift-ecosystem
  repo: provider-certification-plugins
