base_images:
  ocp_base-rhel9:
    name: "5.1"
    namespace: ocp
    tag: base-rhel9
  ocp_cli:
    name: "5.1"
    namespace: ocp
    tag: cli
build_root:
  from_repository: true
  use_build_cache: true
images:
  items:
  - capabilities:
    - intranet
    dockerfile_path: images/installer/Dockerfile.ci
    to: installer
  - capabilities:
    - intranet
    dockerfile_path: images/installer/Dockerfile.upi.ci
    to: upi-installer
releases:
  initial:
    integration:
      name: "5.1"
      namespace: ocp
  latest:
    integration:
      include_built_images: true
      name: "5.1"
      namespace: ocp
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
  installer:
    requests:
      cpu: "3"
      memory: 5Gi
  upi-installer:
    requests:
      cpu: "3"
      memory: 5Gi
tests:
- as: e2e-external-aws-capi
  cron: 17 4 * * 2,5
  steps:
    cluster_profile: openshift-org-aws
    workflow: platform-external-capi-aws
- as: e2e-external-oci-capi
  capabilities:
  - intranet
  cron: 47 5 * * 3
  steps:
    cluster_profile: oci-agent-qe
    env:
      PLATFORM_EXTERNAL_CAPI_INFRA_ONLY: "true"
    workflow: platform-external-capi-oci
zz_generated_metadata:
  branch: release-5.1
  org: openshift
  repo: installer
  variant: periodics
